# Generated by Django 3.2.19 on 2023-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.CharField(max_length=100)),
                ('text_question', models.TextField(unique=True)),
                ('text_answer', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
